### ISSUE TITLE
SITE MESSED UP

### ISSUE THREAD

**Issue by trafort** [gitcowor/prixy#15]
@rajeshdh  or anyone
Sorry, If you can. May you pleas ehelp fix thesse erros kind man?

**Comment by Narulacodes** [comment]
Sorry @trafort.

**Comment by rajeshdh** [comment]
What went wrong?

**Comment by Narulacodes** [comment]
I pulled some Pull rquest to the wrong brance, all commits ever in again.
Everythign is wrong. 

maybe i can create a new repo?

**Comment by rajeshdh** [comment]
Or you can just copy the one I created.

**Comment by SheepTester** [comment]
Check your HTML. You failed to close a script tag on [line 17](https://github.com/gitcowor/prixy/blob/master/index.html#L17) (from 2b56c81ad614b959838b495ec0587ccc36ceed2f). You can see who did this from the [git blame](https://github.com/gitcowor/prixy/blame/1c5ff3e151124efa83cd9dab3023ffb244657092/index.html#L17).

I strongly suggest locally opening the HTML and seeing if it works before merging the pull request.

**Comment by Narulacodes** [comment]
Oh so My Consolewarn.js caused the prob. Thanks @SheepTester. 
I  can't do this now, may you plz create a Pulll request.


@rajeshdh  I don't copy work, even though you helped me. Sorry :)

**Comment by Narulacodes** [comment]
Issue Fixed. Thanks @SheepTester
