### ISSUE TITLE
Make other sections more discoverable

### ISSUE THREAD

**Issue by SheepTester** [gitcowor/prixy#17]
**Is your feature request related to a problem? Please describe.**
It is related to a problem. The problem is that the other sections' existence isn't really obvious; I just found out that there were more sections before making this issue.

**Describe the solution you'd like**
There should be some tabs at the top that stay at the top when you scroll down; each tab links to a different section.

**Describe alternatives you've considered**
There are a few alternatives:
- be able to collapse sections
  - However, if the first section is expanded by default, it doesn't really solve the aforementioned problem.
- a table of contents
  - It's not really obvious where this would fit with the current design, since tables of contents typically are pretty long vertically.
- a dialogue reminding the user that other sections exist
  - This is annoying and unnecessary. It also doesn't even try to help the user get to those sections.

**Additional context**
I am indeed a human, not a spambot.

**Comment by Narulacodes** [comment]
If You can do a pull request, it would be nice, This is  community hand-held project. i do some work, aand ppl put   pull requests and help. What are ways i can do this?
