### ISSUE TITLE
[REMOVED ISSUE]

### ISSUE THREAD

**Issue by Narulacodes** [gitcowor/prixy#2]
REMOVED

**Comment by rajeshdh** [comment]
Hi, I would love to contribute. Let me know how?

**Comment by Narulacodes** [comment]
Sure. um, The thing won;t show on The html page.
,....

**Comment by rajeshdh** [comment]
Okay, What do we want to do here? The javascript code is not complete; it is missing some functions. I can make it work, and I need to know how it is supposed to look like.

**Comment by Narulacodes** [comment]
yeah, plz do that if you can. Thanks :)

**Comment by Narulacodes** [comment]
@rajeshdh  Messed up few things. may you help plz?

**Comment by trafort** [comment]
Closing due to Major Site MESSup due to @Narulacodes
